eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: LOGIN-SERVICE
        uri: http://localhost:7001/
        predicates:
          - Path=/authenticate/**
      - id: ADVERTISE-SERVICE
        uri: http://localhost:9001/
        predicates:
          - Path=/advertise/**
          - Path=/uploadFile
          - Path=/downloadFile/**
    